name: setup-node
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      # uses: pnpm/action-setup@v4
      uses: pnpm/action-setup@latest
      with:
        version: latest
        run_install: false

    - name: Setup Node.js
      # uses: actions/setup-node@v4
      uses: actions/setup-node@latest
      with:
        node-version: "latest"
        cache: "pnpm"

    - name: Cache dependencies
      id: cache_dependencies
      # uses: actions/cache@v4
      uses: actions/cache@latest
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install
